### ISSUE TITLE
Add method for locking using SQL databse.

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-plugin-interface#3]
Remember that lock keys have a limited length in SQL dbs, so whatever the actual key is, we must acquire the lock on its hash

- For SQL, we are going to only use transaction and other database properties for achieve thread safety.
- For SQLite, we are going to use in memory locks in Java
- For NoSQL, see related issue: https://github.com/supertokens/supertokens-core/issues/91

**Comment by rishabhpoddar** [comment]
The kinds of locking we want:
1. Read a value, do some operation, insert / update / delete that value based on the operation
   - The value read may or may not exist.
2. Make sure primary key being inserted is unique.
3. Make sure some non-primary key being inserted is unique

**Comment by bhumilsarvaiya** [comment]
The default isolation level in MySQL is `Repeatable Reads`. The behavior of insert, update and delete for this isolation level when used with `SELECT ... FOR UPDATE` query are as follows:
> **Note**: we assume both the transactions, ***T1*** and ***T2*** started at nearly same time
### Repeatable Reads
- **Insert**
   - T1: (transaction 1)
      - Start transaction
      - Select for update
      - Sleep (10)
      - Insert
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select for update
      - Sleep (15)
      - Insert
      - Commit
    > T2 throws deadlock error while inserting. `SELECT ... FOR UPDATE` in both ***T1*** and ***T2*** returns null value as success.

- **Update**
   - T1: (transaction 1)
      - Start transaction
      - Select for update
      - Sleep (10)
      - Update
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select for update
      - Sleep (15)
      - Update
      - Commit
   > The `SELECT ... FOR UPDATE` in ***T2*** reads the updated value from the ***T1*** transaction. Final value will be equal to the value updated by ***T2*** transaction.

- **Delete**
   - T1: (transaction 1)
      - Start transaction
      - Select for update
      - Sleep (10)
      - Delete
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select for update
      - Sleep (15)
      - Delete
      - Commit
  >  `SELECT ... FOR UPDATE` in ***T2*** transaction will return empty result as it waited for the ***T1*** transaction to commit which deleted the data. No error thrown.

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya thanks. Please do the same for other isolation levels as well

**Comment by bhumilsarvaiya** [comment]
For isolation level `Read Repeatable` if the `SELECT` query does not have `FOR UPDATE` clause, the behavior of insert, update and delete are as follows:

### Repeatable Reads (**without for update**)
- **Insert**
   - T1: (transaction 1)
      - Start transaction
      - Select
      - Sleep (10)
      - Insert
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select
      - Sleep (15)
      - Insert
      - Commit
    > T2 throws duplicate entry error. `SELECT` in both ***T1*** and ***T2*** returns null value as success.

- **Update**
   - T1: (transaction 1)
      - Start transaction
      - Select
      - Sleep (10)
      - Update
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select
      - Sleep (15)
      - Update
      - Commit
   > The `SELECT` in both ***T1*** and ***T2*** reads the same initial value. Final value will be equal to the value updated by ***T2*** transaction.

- **Delete**
   - T1: (transaction 1)
      - Start transaction
      - Select
      - Sleep (10)
      - Delete
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select
      - Sleep (15)
      - Delete
      - Commit
  >  `SELECT` in both ***T1*** and ***T2*** reads the same initial value. No error thrown.

**Comment by bhumilsarvaiya** [comment]
### Read Uncommitted
- **Insert**
   - T1: (transaction 1)
      - Start transaction
      - Select for update
      - Sleep (10)
      - Insert
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select for update
      - Sleep (15)
      - Insert
      - Commit
    > T2 throws duplicate entry error. `SELECT ... FOR UPDATE` in both ***T1*** and ***T2*** returns null value as success.

- **Update**
   - T1: (transaction 1)
      - Start transaction
      - Select for update
      - Sleep (10)
      - Update
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select for update
      - Sleep (15)
      - Update
      - Commit
   > The `SELECT ... FOR UPDATE` in ***T2*** reads the updated value from the ***T1*** transaction. Final value will be equal to the value updated by ***T2*** transaction.

- **Delete**
   - T1: (transaction 1)
      - Start transaction
      - Select for update
      - Sleep (10)
      - Delete
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select for update
      - Sleep (15)
      - Delete
      - Commit
  >  `SELECT ... FOR UPDATE` in ***T2*** transaction will return empty result as it waited for the ***T1*** transaction to commit which deleted the data. No error thrown.

**Comment by bhumilsarvaiya** [comment]
### Read Uncommitted (**without for update**)
- **Insert**
   - T1: (transaction 1)
      - Start transaction
      - Select
      - Sleep (10)
      - Insert
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select
      - Sleep (15)
      - Insert
      - Commit
    > T2 throws duplicate entry error. `SELECT` in both ***T1*** and ***T2*** returns null value as success.

- **Update**
   - T1: (transaction 1)
      - Start transaction
      - Select
      - Sleep (10)
      - Update
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select
      - Sleep (15)
      - Update
      - Commit
   > The `SELECT` in both ***T1*** and ***T2*** reads the same initial value. Final value will be equal to the value updated by ***T2*** transaction.

- **Delete**
   - T1: (transaction 1)
      - Start transaction
      - Select
      - Sleep (10)
      - Delete
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select
      - Sleep (15)
      - Delete
      - Commit
  >  `SELECT` in both ***T1*** and ***T2*** reads the same initial value. No error thrown.

**Comment by bhumilsarvaiya** [comment]
### Read Committed
- **Insert**
   - T1: (transaction 1)
      - Start transaction
      - Select for update
      - Sleep (10)
      - Insert
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select for update
      - Sleep (15)
      - Insert
      - Commit
    > T2 throws duplicate entry error. `SELECT ... FOR UPDATE` in both ***T1*** and ***T2*** returns null value as success.

- **Update**
   - T1: (transaction 1)
      - Start transaction
      - Select for update
      - Sleep (10)
      - Update
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select for update
      - Sleep (15)
      - Update
      - Commit
   > The `SELECT ... FOR UPDATE` in ***T2*** reads the updated value from the ***T1*** transaction. Final value will be equal to the value updated by ***T2*** transaction.

- **Delete**
   - T1: (transaction 1)
      - Start transaction
      - Select for update
      - Sleep (10)
      - Delete
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select for update
      - Sleep (15)
      - Delete
      - Commit
  >  `SELECT ... FOR UPDATE` in ***T2*** transaction will return empty result as it waited for the ***T1*** transaction to commit which deleted the data. No error thrown.

**Comment by bhumilsarvaiya** [comment]
### Read Committed (**without for update**)
- **Insert**
   - T1: (transaction 1)
      - Start transaction
      - Select
      - Sleep (10)
      - Insert
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select
      - Sleep (15)
      - Insert
      - Commit
    > T2 throws duplicate entry error. `SELECT` in both ***T1*** and ***T2*** returns null value as success.

- **Update**
   - T1: (transaction 1)
      - Start transaction
      - Select
      - Sleep (10)
      - Update
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select
      - Sleep (15)
      - Update
      - Commit
   > The `SELECT` in both ***T1*** and ***T2*** reads the same initial value. Final value will be equal to the value updated by ***T2*** transaction.

- **Delete**
   - T1: (transaction 1)
      - Start transaction
      - Select
      - Sleep (10)
      - Delete
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select
      - Sleep (15)
      - Delete
      - Commit
  >  `SELECT` in both ***T1*** and ***T2*** reads the same initial value. No error thrown.

**Comment by bhumilsarvaiya** [comment]
### Serailizable
- **Insert**
   - T1: (transaction 1)
      - Start transaction
      - Select for update
      - Sleep (10)
      - Insert
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select for update
      - Sleep (15)
      - Insert
      - Commit
    > T2 throws deadlock error while inserting. `SELECT ... FOR UPDATE` in both ***T1*** and ***T2*** returns null value as success.

- **Update**
   - T1: (transaction 1)
      - Start transaction
      - Select for update
      - Sleep (10)
      - Update
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select for update
      - Sleep (15)
      - Update
      - Commit
   > The `SELECT ... FOR UPDATE` in ***T2*** reads the updated value from the ***T1*** transaction. Final value will be equal to the value updated by ***T2*** transaction.

- **Delete**
   - T1: (transaction 1)
      - Start transaction
      - Select for update
      - Sleep (10)
      - Delete
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select for update
      - Sleep (15)
      - Delete
      - Commit
  >  `SELECT ... FOR UPDATE` in ***T2*** transaction will return empty result as it waited for the ***T1*** transaction to commit which deleted the data. No error thrown.

**Comment by bhumilsarvaiya** [comment]
### Serializable (**without for update**)
- **Insert**
   - T1: (transaction 1)
      - Start transaction
      - Select
      - Sleep (10)
      - Insert
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select
      - Sleep (15)
      - Insert
      - Commit
    > T2 throws deadlock error while inserting. `SELECT` in both ***T1*** and ***T2*** returns null value as success.

- **Update**
   - T1: (transaction 1)
      - Start transaction
      - Select
      - Sleep (10)
      - Update
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select
      - Sleep (15)
      - Update
      - Commit
   > The `SELECT` in both ***T1*** and ***T2*** reads the same initial value. Final value will be equal to the value updated by ***T2*** transaction.

- **Delete**
   - T1: (transaction 1)
      - Start transaction
      - Select
      - Sleep (10)
      - Delete
      - Commit
   - T2: (transaction 2)
      - Start transaction
      - Select
      - Sleep (15)
      - Delete
      - Commit
  >  `SELECT` in both ***T1*** and ***T2*** reads the same initial value. No error thrown.

**Comment by bhumilsarvaiya** [comment]
## Advisory Locks
An advisory lock is a cooperative lock. An advisory lock has no power to prevent data access by other clients, but instead is based on the concept that all clients will use an agreed-upon convention to cooperate for use of a resource. The convention is the lock name, which is simply a string.

### MySQL
#### ```GET_LOCK(str, timeout)```
- Tries to obtain a lock with a name given by the string str, using a timeout of timeout seconds.
- A negative timeout value means infinite timeout. The lock is exclusive.
- While held by one session, other sessions cannot obtain a lock of the same name.
- A lock obtained with ```GET_LOCK()``` is released explicitly by executing ```RELEASE_LOCK()``` or implicitly when your session terminates (either normally or abnormally).
- Locks obtained with ```GET_LOCK()``` are not released when transactions commit or roll back.
- It is even possible for a given session to acquire multiple locks for the same name. Other sessions cannot acquire a lock with that name until the acquiring session releases all its locks for the name. 
> In MySQL 5.7, ```GET_LOCK()``` was reimplemented using the metadata locking (MDL) subsystem and its capabilities were extended. Multiple simultaneous locks can be acquired and ```GET_LOCK()``` does not release any existing locks. In MySQL 5.6, ```GET_LOCK()``` permitted acquisition of only one named lock at a time, and a second ```GET_LOCK()``` call released any existing lock. The changes made for this function in MySQL 5.7 makes it incompatible with the ```GET_LOCK()``` function of MySQL 5.6.

### PostgreSQL
- There are two ways to acquire an advisory lock in PostgreSQL: at **session level** or at **transaction level**,  meaning if acquired within a transaction, an advisory lock will be automatically released.
- Once acquired at session level, an advisory lock is held until explicitly released or the session ends.
- Unlike standard lock requests, **session-level advisory lock requests do not honor transaction semantics**:
  - a lock acquired during a transaction that is later rolled back will still be held following the rollback
  - an unlock is effective even if the calling transaction fails later.
- A lock can be acquired multiple times by its owning process; for each completed lock request there must be a corresponding unlock request before the lock is actually released.
- Transaction-level lock requests, on the other hand, behave more like regular lock requests: they are automatically released at the end of the transaction, and there is no explicit unlock operation.
#### ```pg_try_advisory_lock(key)```
- It is the PostgreSQL function that will try to obtain the lock.
- If the lock is successfully obtained, PostgreSQL will return 't', otherwise 'f' if you failed you obtain the lock.
- It will not wait until it can obtain the lock, it will return immediately with 't' or 'f'.
- They are reference counted, so we can obtain a lock N times, but must release it N times for another process to acquire it.
- Calling ```SELECT pg_advisory_unlock_all()``` will unlock all advisory locks currently held by you in your session.
- Calling ```SELECT pg_advisory_unlock(n)``` will release one lock reference for the id n.
